export const COUNTRY_CODES = [
  {code: 'ad', name: 'Andorra', phone: '376'},
  {code: 'ae', name: 'United Arab Emirates', phone: '971'},
  {code: 'af', name: 'Afghanistan', phone: '93'},
  {code: 'ag', name: 'Antigua and Barbuda', phone: '1-268'},
  {code: 'ai', name: 'Anguilla', phone: '1-264'},
  {code: 'al', name: 'Albania', phone: '355'},
  {code: 'am', name: 'Armenia', phone: '374'},
  {code: 'ao', name: 'Angola', phone: '244'},
  {code: 'aq', name: 'Antarctica', phone: ''},
  {code: 'ar', name: 'Argentina', phone: '54'},
  {code: 'as', name: 'American Samoa', phone: '1-684'},
  {code: 'at', name: 'Austria', phone: '43'},
  {code: 'au', name: 'Australia', phone: '61'},
  {code: 'aw', name: 'Aruba', phone: '297'},
  {code: 'ax', name: 'Åland Islands', phone: '358-18'},
  {code: 'az', name: 'Azerbaijan', phone: '994'},
  {code: 'ba', name: 'Bosnia and Herzegovina', phone: '387'},
  {code: 'bb', name: 'Barbados', phone: '1-246'},
  {code: 'bd', name: 'Bangladesh', phone: '880'},
  {code: 'be', name: 'Belgium', phone: '32'},
  {code: 'bf', name: 'Burkina Faso', phone: '226'},
  {code: 'bg', name: 'Bulgaria', phone: '359'},
  {code: 'bh', name: 'Bahrain', phone: '973'},
  {code: 'bi', name: 'Burundi', phone: '257'},
  {code: 'bj', name: 'Benin', phone: '229'},
  {code: 'bl', name: 'Saint Barthélemy', phone: '590'},
  {code: 'bm', name: 'Bermuda', phone: '1-441'},
  {code: 'bn', name: 'Brunei', phone: '673'},
  {code: 'bo', name: 'Bolivia', phone: '591'},
  {code: 'bq', name: 'Caribbean Netherlands', phone: '599'},
  {code: 'br', name: 'Brazil', phone: '55'},
  {code: 'bs', name: 'Bahamas', phone: '1-242'},
  {code: 'bt', name: 'Bhutan', phone: '975'},
  {code: 'bv', name: 'Bouvet Island', phone: ''},
  {code: 'bw', name: 'Botswana', phone: '267'},
  {code: 'by', name: 'Belarus', phone: '375'},
  {code: 'bz', name: 'Belize', phone: '501'},
  {code: 'ca', name: 'Canada', phone: '1'},
  {code: 'cc', name: 'Cocos (Keeling) Islands', phone: '61'},
  {code: 'cd', name: 'DR Congo', phone: '243'},
  {code: 'cf', name: 'Central African Republic', phone: '236'},
  {code: 'cg', name: 'Republic of the Congo', phone: '242'},
  {code: 'ch', name: 'Switzerland', phone: '41'},
  {code: 'ci', name: 'Côte d\'Ivoire (Ivory Coast)', phone: '225'},
  {code: 'ck', name: 'Cook Islands', phone: '682'},
  {code: 'cl', name: 'Chile', phone: '56'},
  {code: 'cm', name: 'Cameroon', phone: '237'},
  {code: 'cn', name: 'China', phone: '86'},
  {code: 'co', name: 'Colombia', phone: '57'},
  {code: 'cr', name: 'Costa Rica', phone: '506'},
  {code: 'cu', name: 'Cuba', phone: '53'},
  {code: 'cv', name: 'Cape Verde', phone: '238'},
  {code: 'cw', name: 'Curaçao', phone: '599'},
  {code: 'cx', name: 'Christmas Island', phone: '61'},
  {code: 'cy', name: 'Cyprus', phone: '357'},
  {code: 'cz', name: 'Czechia', phone: '420'},
  {code: 'de', name: 'Germany', phone: '49'},
  {code: 'dj', name: 'Djibouti', phone: '253'},
  {code: 'dk', name: 'Denmark', phone: '45'},
  {code: 'dm', name: 'Dominica', phone: '1-767'},
  {code: 'do', name: 'Dominican Republic', phone: '1-809 and 1-829'},
  {code: 'dz', name: 'Algeria', phone: '213'},
  {code: 'ec', name: 'Ecuador', phone: '593'},
  {code: 'ee', name: 'Estonia', phone: '372'},
  {code: 'eg', name: 'Egypt', phone: '20'},
  {code: 'eh', name: 'Western Sahara', phone: '212'},
  {code: 'er', name: 'Eritrea', phone: '291'},
  {code: 'es', name: 'Spain', phone: '34'},
  {code: 'et', name: 'Ethiopia', phone: '251'},
  {code: 'eu', name: 'European Union'},
  {code: 'fi', name: 'Finland', phone: '358'},
  {code: 'fj', name: 'Fiji', phone: '679'},
  {code: 'fk', name: 'Falkland Islands', phone: '500'},
  {code: 'fm', name: 'Micronesia', phone: '691'},
  {code: 'fo', name: 'Faroe Islands', phone: '298'},
  {code: 'fr', name: 'France', phone: '33'},
  {code: 'ga', name: 'Gabon', phone: '241'},
  {code: 'gb', name: 'United Kingdom', phone: '44'},
  {code: 'gb-eng', name: 'England'},
  {code: 'gb-nir', name: 'Northern Ireland'},
  {code: 'gb-sct', name: 'Scotland'},
  {code: 'gb-wls', name: 'Wales'},
  {code: 'gd', name: 'Grenada', phone: '1-473'},
  {code: 'ge', name: 'Georgia', phone: '995'},
  {code: 'gf', name: 'French Guiana', phone: '594'},
  {code: 'gg', name: 'Guernsey', phone: '44-1481'},
  {code: 'gh', name: 'Ghana', phone: '233'},
  {code: 'gi', name: 'Gibraltar', phone: '350'},
  {code: 'gl', name: 'Greenland', phone: '299'},
  {code: 'gm', name: 'Gambia', phone: '220'},
  {code: 'gn', name: 'Guinea', phone: '224'},
  {code: 'gp', name: 'Guadeloupe', phone: '590'},
  {code: 'gq', name: 'Equatorial Guinea', phone: '240'},
  {code: 'gr', name: 'Greece', phone: '30'},
  {code: 'gs', name: 'South Georgia', phone: ''},
  {code: 'gt', name: 'Guatemala', phone: '502'},
  {code: 'gu', name: 'Guam', phone: '1-671'},
  {code: 'gw', name: 'Guinea-Bissau', phone: '245'},
  {code: 'gy', name: 'Guyana', phone: '592'},
  {code: 'hk', name: 'Hong Kong', phone: '852'},
  {code: 'hm', name: 'Heard Island and McDonald Islands'},
  {code: 'hn', name: 'Honduras', phone: '504'},
  {code: 'hr', name: 'Croatia', phone: '385'},
  {code: 'ht', name: 'Haiti', phone: '509'},
  {code: 'hu', name: 'Hungary', phone: '36'},
  {code: 'id', name: 'Indonesia', phone: '62'},
  {code: 'ie', name: 'Ireland', phone: '353'},
  {code: 'il', name: 'Israel', phone: '972'},
  {code: 'im', name: 'Isle of Man', phone: '44-1624'},
  {code: 'in', name: 'India', phone: '91'},
  {code: 'io', name: 'British Indian Ocean Territory', phone: '246'},
  {code: 'iq', name: 'Iraq', phone: '964'},
  {code: 'ir', name: 'Iran', phone: '98'},
  {code: 'is', name: 'Iceland', phone: '354'},
  {code: 'it', name: 'Italy', phone: '39'},
  {code: 'je', name: 'Jersey', phone: '44-1534'},
  {code: 'jm', name: 'Jamaica', phone: '1-876'},
  {code: 'jo', name: 'Jordan', phone: '962'},
  {code: 'jp', name: 'Japan', phone: '81'},
  {code: 'ke', name: 'Kenya', phone: '254'},
  {code: 'kg', name: 'Kyrgyzstan', phone: '996'},
  {code: 'kh', name: 'Cambodia', phone: '855'},
  {code: 'ki', name: 'Kiribati', phone: '686'},
  {code: 'km', name: 'Comoros', phone: '269'},
  {code: 'kn', name: 'Saint Kitts and Nevis', phone: '1-869'},
  {code: 'kp', name: 'North Korea', phone: '850'},
  {code: 'kr', name: 'South Korea', phone: '82'},
  {code: 'kw', name: 'Kuwait', phone: '965'},
  {code: 'ky', name: 'Cayman Islands', phone: '1-345'},
  {code: 'kz', name: 'Kazakhstan', phone: '7'},
  {code: 'la', name: 'Laos', phone: '856'},
  {code: 'lb', name: 'Lebanon', phone: '961'},
  {code: 'lc', name: 'Saint Lucia', phone: '1-758'},
  {code: 'li', name: 'Liechtenstein', phone: '423'},
  {code: 'lk', name: 'Sri Lanka', phone: '94'},
  {code: 'lr', name: 'Liberia', phone: '231'},
  {code: 'ls', name: 'Lesotho', phone: '266'},
  {code: 'lt', name: 'Lithuania', phone: '370'},
  {code: 'lu', name: 'Luxembourg', phone: '352'},
  {code: 'lv', name: 'Latvia', phone: '371'},
  {code: 'ly', name: 'Libya', phone: '218'},
  {code: 'ma', name: 'Morocco', phone: '212'},
  {code: 'mc', name: 'Monaco', phone: '377'},
  {code: 'md', name: 'Moldova', phone: '373'},
  {code: 'me', name: 'Montenegro', phone: '382'},
  {code: 'mf', name: 'Saint Martin', phone: '590'},
  {code: 'mg', name: 'Madagascar', phone: '261'},
  {code: 'mh', name: 'Marshall Islands', phone: '692'},
  {code: 'mk', name: 'North Macedonia', phone: '389'},
  {code: 'ml', name: 'Mali', phone: '223'},
  {code: 'mm', name: 'Myanmar', phone: '95'},
  {code: 'mn', name: 'Mongolia', phone: '976'},
  {code: 'mo', name: 'Macau', phone: '853'},
  {code: 'mp', name: 'Northern Mariana Islands', phone: '1-670'},
  {code: 'mq', name: 'Martinique', phone: '596'},
  {code: 'mr', name: 'Mauritania', phone: '222'},
  {code: 'ms', name: 'Montserrat', phone: '1-664'},
  {code: 'mt', name: 'Malta', phone: '356'},
  {code: 'mu', name: 'Mauritius', phone: '230'},
  {code: 'mv', name: 'Maldives', phone: '960'},
  {code: 'mw', name: 'Malawi', phone: '265'},
  {code: 'mx', name: 'Mexico', phone: '52'},
  {code: 'my', name: 'Malaysia', phone: '60'},
  {code: 'mz', name: 'Mozambique', phone: '258'},
  {code: 'na', name: 'Namibia', phone: '264'},
  {code: 'nc', name: 'New Caledonia', phone: '687'},
  {code: 'ne', name: 'Niger', phone: '227'},
  {code: 'nf', name: 'Norfolk Island', phone: '672'},
  {code: 'ng', name: 'Nigeria', phone: '234'},
  {code: 'ni', name: 'Nicaragua', phone: '505'},
  {code: 'nl', name: 'Netherlands', phone: '31'},
  {code: 'no', name: 'Norway', phone: '47'},
  {code: 'np', name: 'Nepal', phone: '977'},
  {code: 'nr', name: 'Nauru', phone: '674'},
  {code: 'nu', name: 'Niue', phone: '683'},
  {code: 'nz', name: 'New Zealand', phone: '64'},
  {code: 'om', name: 'Oman', phone: '968'},
  {code: 'pa', name: 'Panama', phone: '507'},
  {code: 'pe', name: 'Peru', phone: '51'},
  {code: 'pf', name: 'French Polynesia', phone: '689'},
  {code: 'pg', name: 'Papua New Guinea', phone: '675'},
  {code: 'ph', name: 'Philippines', phone: '63'},
  {code: 'pk', name: 'Pakistan', phone: '92'},
  {code: 'pl', name: 'Poland', phone: '48'},
  {code: 'pm', name: 'Saint Pierre and Miquelon', phone: '508'},
  {code: 'pn', name: 'Pitcairn Islands', phone: '870'},
  {code: 'pr', name: 'Puerto Rico', phone: '1-787 and 1-939'},
  {code: 'ps', name: 'Palestine', phone: '970'},
  {code: 'pt', name: 'Portugal', phone: '351'},
  {code: 'pw', name: 'Palau', phone: '680'},
  {code: 'py', name: 'Paraguay', phone: '595'},
  {code: 'qa', name: 'Qatar', phone: '974'},
  {code: 're', name: 'Réunion', phone: '262'},
  {code: 'ro', name: 'Romania', phone: '40'},
  {code: 'rs', name: 'Serbia', phone: '381'},
  {code: 'ru', name: 'Russia', phone: '7'},
  {code: 'rw', name: 'Rwanda', phone: '250'},
  {code: 'sa', name: 'Saudi Arabia', phone: '966'},
  {code: 'sb', name: 'Solomon Islands', phone: '677'},
  {code: 'sc', name: 'Seychelles', phone: '248'},
  {code: 'sd', name: 'Sudan', phone: '249'},
  {code: 'se', name: 'Sweden', phone: '46'},
  {code: 'sg', name: 'Singapore', phone: '65'},
  {code: 'sh', name: 'Saint Helena, Ascension and Tristan da Cunha', phone: '290'},
  {code: 'si', name: 'Slovenia', phone: '386'},
  {code: 'sj', name: 'Svalbard and Jan Mayen', phone: '47'},
  {code: 'sk', name: 'Slovakia', phone: '421'},
  {code: 'sl', name: 'Sierra Leone', phone: '232'},
  {code: 'sm', name: 'San Marino', phone: '378'},
  {code: 'sn', name: 'Senegal', phone: '221'},
  {code: 'so', name: 'Somalia', phone: '252'},
  {code: 'sr', name: 'Suriname', phone: '597'},
  {code: 'ss', name: 'South Sudan', phone: '211'},
  {code: 'st', name: 'São Tomé and Príncipe', phone: '239'},
  {code: 'sv', name: 'El Salvador', phone: '503'},
  {code: 'sx', name: 'Sint Maarten', phone: '599'},
  {code: 'sy', name: 'Syria', phone: '963'},
  {code: 'sz', name: 'Eswatini (Swaziland)', phone: '268'},
  {code: 'tc', name: 'Turks and Caicos Islands', phone: '1-649'},
  {code: 'td', name: 'Chad', phone: '235'},
  {code: 'tf', name: 'French Southern and Antarctic Lands', phone: ''},
  {code: 'tg', name: 'Togo', phone: '228'},
  {code: 'th', name: 'Thailand', phone: '66'},
  {code: 'tj', name: 'Tajikistan', phone: '992'},
  {code: 'tk', name: 'Tokelau', phone: '690'},
  {code: 'tl', name: 'Timor-Leste', phone: '670'},
  {code: 'tm', name: 'Turkmenistan', phone: '993'},
  {code: 'tn', name: 'Tunisia', phone: '216'},
  {code: 'to', name: 'Tonga', phone: '676'},
  {code: 'tr', name: 'Turkey', phone: '90'},
  {code: 'tt', name: 'Trinidad and Tobago', phone: '1-868'},
  {code: 'tv', name: 'Tuvalu', phone: '688'},
  {code: 'tw', name: 'Taiwan', phone: '886'},
  {code: 'tz', name: 'Tanzania', phone: '255'},
  {code: 'ua', name: 'Ukraine', phone: '380'},
  {code: 'ug', name: 'Uganda', phone: '256'},
  {code: 'um', name: 'United States Minor Outlying Islands', phone: '1'},
  {code: 'un', name: 'United Nations'},
  {code: 'us', name: 'United States', phone: '1'},
  {code: 'us-ak', name: 'Alaska'},
  {code: 'us-al', name: 'Alabama'},
  {code: 'us-ar', name: 'Arkansas'},
  {code: 'us-az', name: 'Arizona'},
  {code: 'us-ca', name: 'California'},
  {code: 'us-co', name: 'Colorado'},
  {code: 'us-ct', name: 'Connecticut'},
  {code: 'us-de', name: 'Delaware'},
  {code: 'us-fl', name: 'Florida'},
  {code: 'us-ga', name: 'Georgia'},
  {code: 'us-hi', name: 'Hawaii'},
  {code: 'us-ia', name: 'Iowa'},
  {code: 'us-id', name: 'Idaho'},
  {code: 'us-il', name: 'Illinois'},
  {code: 'us-in', name: 'Indiana'},
  {code: 'us-ks', name: 'Kansas'},
  {code: 'us-ky', name: 'Kentucky'},
  {code: 'us-la', name: 'Louisiana'},
  {code: 'us-ma', name: 'Massachusetts'},
  {code: 'us-md', name: 'Maryland'},
  {code: 'us-me', name: 'Maine'},
  {code: 'us-mi', name: 'Michigan'},
  {code: 'us-mn', name: 'Minnesota'},
  {code: 'us-mo', name: 'Missouri'},
  {code: 'us-ms', name: 'Mississippi'},
  {code: 'us-mt', name: 'Montana'},
  {code: 'us-nc', name: 'North Carolina'},
  {code: 'us-nd', name: 'North Dakota'},
  {code: 'us-ne', name: 'Nebraska'},
  {code: 'us-nh', name: 'New Hampshire'},
  {code: 'us-nj', name: 'New Jersey'},
  {code: 'us-nm', name: 'New Mexico'},
  {code: 'us-nv', name: 'Nevada'},
  {code: 'us-ny', name: 'New York'},
  {code: 'us-oh', name: 'Ohio'},
  {code: 'us-ok', name: 'Oklahoma'},
  {code: 'us-or', name: 'Oregon'},
  {code: 'us-pa', name: 'Pennsylvania'},
  {code: 'us-ri', name: 'Rhode Island'},
  {code: 'us-sc', name: 'South Carolina'},
  {code: 'us-sd', name: 'South Dakota'},
  {code: 'us-tn', name: 'Tennessee'},
  {code: 'us-tx', name: 'Texas'},
  {code: 'us-ut', name: 'Utah'},
  {code: 'us-va', name: 'Virginia'},
  {code: 'us-vt', name: 'Vermont'},
  {code: 'us-wa', name: 'Washington'},
  {code: 'us-wi', name: 'Wisconsin'},
  {code: 'us-wv', name: 'West Virginia'},
  {code: 'us-wy', name: 'Wyoming'},
  {code: 'uy', name: 'Uruguay', phone: '598'},
  {code: 'uz', name: 'Uzbekistan', phone: '998'},
  {code: 'va', name: 'Vatican City (Holy See)', phone: '379'},
  {code: 'vc', name: 'Saint Vincent and the Grenadines', phone: '1-784'},
  {code: 've', name: 'Venezuela', phone: '58'},
  {code: 'vg', name: 'British Virgin Islands', phone: '1-284'},
  {code: 'vi', name: 'United States Virgin Islands', phone: '1-340'},
  {code: 'vn', name: 'Vietnam', phone: '84'},
  {code: 'vu', name: 'Vanuatu', phone: '678'},
  {code: 'wf', name: 'Wallis and Futuna', phone: '681'},
  {code: 'ws', name: 'Samoa', phone: '685'},
  {code: 'xk', name: 'Kosovo', phone: ''},
  {code: 'ye', name: 'Yemen', phone: '967'},
  {code: 'yt', name: 'Mayotte', phone: '262'},
  {code: 'za', name: 'South Africa', phone: '27'},
  {code: 'zm', name: 'Zambia', phone: '260'},
  {code: 'zw', name: 'Zimbabwe', phone: '263'}
];
